language: cpp
compiler:
  - gcc
  - clang
before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
        - sudo apt-get install -qq qt5-qmake qtbase5-dev
        - sudo apt-get install libgtest-dev
script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ctest
notifications:
        recipients:
                - doc@methedrine.org
        email:
                on_success: change
                on_failure: always
