language: cpp
compiler:
  - gcc
  - clang
install:
        - sudo apt-get install libgtest-dev
script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ctest
notifications:
        recipients:
                - doc@methedrine.org
        email:
                on_success: change
                on_failure: always
