env:
  global:
   - secure: "D0Zi3FPkQ6zediBNTuwxCIrn3W0amz+kfE0Q7o7JmL77rusY3pFIzhChbDWHflYxOhiHnrFvy8MS9kiMenTyqX/jBl2yyiJRGEqnaWSJ4EDc3kr01MPrpkzZ+/x62s6kWE8YHdTHDAa6dIhXW4fVnWvFTmUO05VW2RoPOdXe7DA="

addons:
  coverity_scan:
    project:
      name: "daehlith/QtGoogleAnalytics"
      description: "A library for integrating Google Analytics in a Qt application"
    notification_email: doc@methedrine.org
    build_command_prepend: cmake ..
    build_command: make
    branch_pattern: coverity_scan

language: cpp
compiler:
  - clang
  - gcc

before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
install:
        - sudo apt-get install -qq qt5-qmake qtbase5-dev
        - sudo apt-get install libgtest-dev
before_script:
        - mkdir .gtest-build
        - cd .gtest-build
        - cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest/
        - make
        - sudo mv libg* /usr/lib/
        - cd ..
        - mkdir .qtgabuild
        - cd .qtgabuild
script: 
        - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then cmake .. && make ; fi
        - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make tests ; fi
after_success:
        - ls -all
        - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./bin/tests ; fi
notifications:
        recipients:
                - doc@methedrine.org
        email:
                on_success: change
                on_failure: always
